#!/usr/bin/env python3
"""Render the federal assessment artifacts from their source-of-truth data.

Reads (all in this directory):
  nist-800-171-rev2-mapping.yaml   the 110-requirement mapping (authored)
  sprs-weights.json                Annex A weights, parsed from the DoD
                                   Assessment Methodology v1.2.1 PDF and
                                   verified to reproduce the -203..+110 range
  fedramp-20x-ksi-mapping.yaml     the 46-KSI CR26 mapping (authored)

Writes (one directory up, in assessment/):
  nist-800-171-rev2-workbook.md
  fedramp-20x-ksi-map.md

Deterministic: same inputs, same output. Run from anywhere:
  python3 assessment/data/render.py
"""
from pathlib import Path
import json
import yaml

HERE = Path(__file__).resolve().parent
OUT = HERE.parent

mapping = yaml.safe_load((HERE / "nist-800-171-rev2-mapping.yaml").read_text())
weights = json.loads((HERE / "sprs-weights.json").read_text())
ksi = yaml.safe_load((HERE / "fedramp-20x-ksi-mapping.yaml").read_text())


def w(rid: str) -> str:
    v = weights[rid]
    return "n/a" if v == "NA" else v


# ---------------------------------------------------------------- workbook --
lines = []
add = lines.append
add("# NIST SP 800-171 Rev 2 self-assessment workbook")
add("")
add("All 110 security requirements, ready to walk on day one. Each row carries "
    "its SPRS weight from the DoD Assessment Methodology v1.2.1, the Living "
    "Control Set control(s) that address it, and the 800-53 anchor that makes "
    "the mapping traceable rather than asserted. The evidence line above each "
    "family names where evidence computes from in Mattermost's publicly "
    "documented stack.")
add("")
add("**What this is not:** an assessment result. No requirement is marked met "
    "or unmet here, and no SPRS score is claimed, because implementation state "
    "is only knowable inside the boundary, from systems of record. The status "
    "column ships empty on purpose; filling it during days 30 to 60 is the "
    "work, and this workbook is the instrument.")
add("")
add("**Regime note:** under the 2026-07-13 CMMC Phase II suspension the "
    "enforced baseline is exactly this document's frame: NIST SP 800-171 Rev 2 "
    "by self-assessment, posted to SPRS, with DFARS 252.204-7012 fully in "
    "force. A posted score is a signed federal claim, which is why every row "
    "below insists on re-derivable evidence.")
add("")
add("**Scoring mechanics:** start at 110, subtract each unimplemented "
    "requirement's weight. 44 requirements weigh 5 points, 14 weigh 3, 51 "
    "weigh 1; two carry partial credit (3.5.3 MFA and 3.13.11 FIPS "
    "cryptography); 3.12.4 (the SSP) is unscored because without an SSP the "
    "assessment cannot be conducted at all. Floor is -203; a perfect score is "
    "110.")
add("")

total_5 = total_3 = total_1 = 0
for fam in mapping["families"]:
    add(f"## {fam['family']} {fam['name']}")
    add("")
    add(f"**Evidence computes from:** {fam['evidence_sources']}")
    if fam.get("family_note"):
        add("")
        add(f"> {fam['family_note']}")
    add("")
    add("| Req | Requirement | SPRS | Living Control Set | Status | Notes |")
    add("|---|---|---|---|---|---|")
    for r in fam["requirements"]:
        rid = str(r["id"])
        v = w(rid)
        if v == "5":
            total_5 += 1
        elif v == "3":
            total_3 += 1
        elif v == "1":
            total_1 += 1
        ctl = ", ".join(r["controls"])
        note = r.get("note", "")
        anchor = r.get("anchor", "")
        note_cell = f"anchor: {anchor}" + (f". {note}" if note else "")
        add(f"| {rid} | {r['name']} | {v} | {ctl} | ☐ assess | {note_cell} |")
    add("")

add("---")
add("")
add(f"**Integrity check:** {total_5} five-point, {total_3} three-point, "
    f"{total_1} one-point requirements plus the unscored SSP requirement "
    f"(3.12.4) = {total_5 + total_3 + total_1 + 1} of 110. Weights parsed "
    "from the methodology PDF itself and verified to reproduce its published "
    "score range exactly.")
add("")
add("*Generated by `assessment/data/render.py` from "
    "`nist-800-171-rev2-mapping.yaml` + `sprs-weights.json`. Edit the data, "
    "never this file.*")
add("")
(OUT / "nist-800-171-rev2-workbook.md").write_text("\n".join(lines))

# ----------------------------------------------------------------- KSI map --
lines = []
add = lines.append
meta = ksi["metadata"]
add("# FedRAMP 20x Key Security Indicator map")
add("")
add(f"Every KSI in the current official set ({meta['framework_name']}, "
    f"{meta['ksi_count']} indicators), mapped to the Living Control Set. The "
    "CR26 release is the authority in force since 24 June 2026 and supersedes "
    "the older 20x phase counts quoted in vendor material; each mapping is "
    "computed first from the SP 800-53 references CR26 itself publishes per "
    "KSI, then curated, and the basis column says which.")
add("")
s = meta["summary"]
add(f"**Coverage: {s['covered']} covered, {s['partial']} partial, "
    f"{s['unaddressed']} unaddressed.** Partial never hides: each names its "
    "modernization delta in the note, because those deltas are the actual "
    "work of a 20x-shaped program. Coverage describes the engine's control "
    "set, never any company's implementation state.")
add("")
add("**Why this matters for this role:** FedRAMP's stated direction is "
    "continuous, machine-validated evidence over point-in-time narrative, "
    "which is the thesis the engine is built on. Mattermost reaches federal "
    "buyers today through a partner's package; if the strategy question ever "
    "resolves toward its own listing, this map is the gap analysis, "
    "pre-built.")
add("")
for cat in ksi["categories"]:
    add(f"## {cat['category']}")
    add("")
    add("| KSI | Indicator | Coverage | Living Control Set | Basis | Delta / note |")
    add("|---|---|---|---|---|---|")
    for x in cat["ksis"]:
        cov = "✅ covered" if x["coverage"] == "covered" else "◐ partial"
        add(f"| {x['id']} | {x['title']} | {cov} | {', '.join(x['controls'])} "
            f"| {x['basis']} | {x.get('note', '')} |")
    add("")
add("---")
add("")
add("*Generated by `assessment/data/render.py` from "
    "`fedramp-20x-ksi-mapping.yaml`. Edit the data, never this file.*")
add("")
(OUT / "fedramp-20x-ksi-map.md").write_text("\n".join(lines))

print("rendered:", OUT / "nist-800-171-rev2-workbook.md")
print("rendered:", OUT / "fedramp-20x-ksi-map.md")
